version: '2'
services:
  server:
    build: ./server
    restart: always
    ports:
      - "3000:3000"
  greeter-service:
    build: ./greeter-service
    restart: always
  adder-service:
    build: ./adder-service
    restart: always